@startuml events
skin rose

Class BeaconSchema {
  +String beaconMPH
  +String beaconTN
}

Class StakeSchema {
  +String stake_addr
  +String[] assets
}

Class EventSchema {
  +String asset
  +String name
  +String location
  +String showtime
  +String image
  +Number allocated
  +Number holding
  +Number released
  +Number converted
  +String holdValHash
  +String paymentPKH
  +String stakePKH
  +String txId
  +Boolean confirmed
  +Boolean active
}

Class SwapSchema {
  +String name
  +String location
  +String showtime
  +String image
  +String description
  +String askedAsset
  +Number askedAssetQty
  +String offeredAsset
  +Number offeredAssetQty
  +String beaconAsset
  +String holdValHash
  +String paymentPKH
  +String stakePKH
  +String ownerPKH
  +Number minLovelace
  +String txId
  +Boolean confirmed
  +Boolean active
}
  
Class TicketSchema {
  +String asset
  +String pkh
  +Boolean used
}

StakeSchema"1" -- "+"EventSchema : has >
EventSchema"1" *-- "+"SwapSchema : has >
SwapSchema"1" -- "1"BeaconSchema : has >
EventSchema"1" -- "+"TicketSchema : has >


@enduml