@startuml mint-tickets

skin rose
header Precondition: Wallet Connected
actor User
User -> Browser : Mint Tickets
Browser -> Wallet : Get UTXOs
Wallet --> Browser : UTXOs
Browser -> Browser : Build Tx [Mint Ticket]
Browser -> Wallet: Sign Tx 
Wallet -> User: Sign Tx
User --> Wallet: Signature (PKH + Stake Key)
Wallet --> Browser : Witness
Browser -> App : Signed Tx
App -> Blockfrost : Submit Tx
Blockfrost -> Blockchain : Submit Tx
Blockfrost --> App : Success (TxId)
App --> Browser : Success (TxId)
Browser -> App : Link Ticket Asset to Stake Key
App -> DB : Link Ticket Asset to to Stake Key
App -> DB : Create Event
Browser --> User : Success (TxId)

   
@enduml