@startuml open-swap

skin rose
header Precondition: Wallet Connected
actor User
User -> Browser : Open Swap
Browser -> Wallet : Get UTXOs
Wallet --> Browser : UTXOs
Browser -> App : Get Event MPHs (stake key hash)
App -> DB : Get Event MPHs (stake key hash)
DB --> App: Active Event MPHs
App --> Browser : Active Event MPHs 
Browser --> User : Active Event MPHs
User -> Browser : Select Event MPH
Browser -> App : Get Ticket UTXO
App -> Blockfrost : Get Ticket UTXO
Blockfrost --> App : Ticket UTXO
App --> Browser : Ticket UTXO
Browser -> Browser : Build Tx [Transfer Tickets, Mint Beacon]
Browser -> Wallet: Sign Tx
Wallet -> User: Sign Tx
User --> Wallet: Signature
Wallet --> Browser : Witness
Browser -> App : Signed Tx
App -> App : Sign Tx
App -> Blockfrost : Submit Tx
Blockfrost -> Blockchain : Submit Tx
Blockfrost --> App : Success (TxId)
App --> Browser : Success (TxId)
Browser --> User : Success (TxId)

   
@enduml