@startuml events
skin rose

Class User {
  + askedAssets
  }

Class Swap {
    + askedAssets
    + offeredAssets
}

User"1" -- "+"Swap : Interacts with >
Swap"1" *-- "+"TicketReleased : has >
Swap"+" *-- "+"TicketConverted : has >

@enduml