@startuml

skin rose

[*] --> Holding : Mint Ticket

Holding --> Released : Open Swap
Holding --> [*] : Burn Ticket

Released --> Converted : Execute Swap
Released --> Released : Update Swap
Released --> Holding : Close Swap

Converted --> PublicKeyHash : Print Ticket

PublicKeyHash --> [*] : Verify Ticket

@enduml