@startuml view-swaps

skin rose
header Precondition: None
actor User
User -> Browser : View Swaps
Browser -> App : Get Swaps
App -> Blockfrost : Get Swaps w/ Beacon MPH
Blockfrost -> Blockchain : Get Swaps w/ Beacon MPH
Blockchain --> Blockfrost : Swap Addresses & Beacon Metadata
Blockfrost --> App : Swap Addresses & Beacon Metadata
App --> Browser : List Swaps
Browser --> User : View Swaps

@enduml