@startuml view-swaps

skin rose
header Precondition: None
actor User

Blockchain -> Blockfrost : Swap Update
Blockfrost -> App : Swap Update
App -> DB : Swap Update
User -> Browser : View Swaps
Browser -> App : Get Swaps
App -> DB : Get Swaps 
DB --> App : Swap List
App --> Browser : Swap List
Browser --> User : Swaps List

@enduml